version: "3"
services:
    nginx:
        image: nginx:latest
        restart: always
        volumes:
            - ./src/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./src/nginx/src:/usr/share/nginx/html
        ports:
            - 80:80
            - 443:443
        depends_on:
            - express-api

    express-api:
        image: express-api
        build: src/express-api
        restart: always
        ports:
            - 3000:3000
