version: "3"
services:
    frontend:
        image: frontend
        build: src/frontend
        restart: always
        ports:
            - 80:80
            - 443:443
        depends_on:
            - express-api

    express-api:
        image: express-api
        build: src/express-api
        restart: always
