# frontend
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: "TCP"
    port: 80 # this is where you'll reach the deployed app ([localhost]:[port] or nginx config [server_name]:[port])
    targetPort: 80 # this is where the frontend is exposed through nginx
  type: LoadBalancer

---

# express-api
apiVersion: v1
kind: Service
metadata:
  name: express-api
spec:
  selector:
    app: express-api
  ports:
  - protocol: "TCP"
    port: 3000 # this is where you'll reach the deployed app ([localhost]:[port]
    targetPort: 3000 # this is where the frontend is exposed through nginx
  type: LoadBalancer